### ISSUE TITLE
Cannot run this app on Linux Mint

### ISSUE THREAD

**Issue by jebedaia360** [Dogeek/renpy-text-editor#18]
I try to run this on Linux Mint 19.3 x64 with python 3.6.9
I made:
` pip3 install -r requirements.txt --upgrade`

But when I try to run:
`python3. -m renpytexteditor.py`

I get this:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/jeremi360/Apps/renpy-text-editor-0.95b/renpytexteditor.py", line 1, in <module>
    from RTE.views.main import RenpyTextEditorGUI
  File "/home/jeremi360/Apps/renpy-text-editor-0.95b/RTE/views/main.py", line 3, in <module>
    from .editor_window import EditorFrame
  File "/home/jeremi360/Apps/renpy-text-editor-0.95b/RTE/views/editor_window.py", line 5, in <module>
    from RTE.config import config
  File "/home/jeremi360/Apps/renpy-text-editor-0.95b/RTE/config.py", line 84, in <module>
    config = Config()
  File "/home/jeremi360/Apps/renpy-text-editor-0.95b/RTE/config.py", line 12, in __init__
    data = json.load(conf)
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 13 column 6 (char 312)
```

**Comment by Dogeek** [comment]
Can you send over the config/config.json file ?

This traceback indicates that the file is not properly formatted JSON, though the default file passes when linted

**Comment by madeddy** [comment]
I have exactly the same on Kubuntu 18.04.3. (Same base OS vers. and py vers.) and RTE-0.95b release.
Found your little bug in the config/config.json. One missing comma and a parens to much:
```
{
    "wm_width": 1270,
    "wm_height": 575,
    "theme_name": "monokai",
    "insert_spaces_instead_of_tabs": true,
    "tabs_length": 4,
    "show_whitespace_characters": false,
    "debug": true,
    "start_maximized": false,
    "locale": "en-US",
    "path_to_git": "",
    "side_notebook_width": 200
}    "scrollbar_width": 20
}
```
I corrected this for my install and get now this error:
```$ python3 -m renpytexteditor.py
/usr/bin/python3: Error while finding module specification for 'renpytexteditor.py' (AttributeError: module 'renpytexteditor' has no attribute '__path__')```

With the sources from current master the json error is gone, but it throws also this error.

**Comment by jebedaia360** [comment]
> Can you send over the config/config.json file ?
> 
> This traceback indicates that the file is not properly formatted JSON, though the default file passes when linted

I don't change `config/config.json` I just try to run it for first time.
```
{
    "wm_width": 1270,
    "wm_height": 575,
    "theme_name": "monokai",
    "insert_spaces_instead_of_tabs": true,
    "tabs_length": 4,
    "show_whitespace_characters": false,
    "debug": true,
    "start_maximized": false,
    "locale": "en-US",
    "path_to_git": "",
    "side_notebook_width": 200
}    "scrollbar_width": 20
}
```
O I see I have one too many brackets.

**Comment by jebedaia360** [comment]
I fix config/config.json and now I get the same result as @madeddy :
```
/usr/bin/python3: Error while finding module specification for 'renpytexteditor.py' (AttributeError: module 'renpytexteditor' has no attribute '__path__')
```

**Comment by Dogeek** [comment]
Will check this out. I have to admit, I'm surprised to see people interested in the project since I haven't worked on it for the past 8 or so months.

**Comment by jebedaia360** [comment]
@Dogeek There are more and more more added renpy games so people will be interest in it :smile: 
I just curious because I make Rakugo is like Ren'Py, but for Godot Engine.

**Comment by Dogeek** [comment]
I just tested it on windows without any issues. It'll take me a while to have access to a linux machine to test it on though.

My best bet is that I didn't put any shebangs in the python files. Are you running the app from the released version, or from source ?

**Comment by madeddy** [comment]
For me both variants like said in my last msg. And to repeat it:
- The json error is with "current" master source gone.
- Running the app without `-m` switch works. So -> `python3 renpytexteditor.py` simply.

The interest? I found it earlie summer by chance and lurked some from there. RTE is something i thought already years ago we should have for the engine. 
Coding to script is fine for me, but there are other people... On top of this i see no benefit in repeating some more often and longer code constructions again and again by hand. Its dumb imo and time consuming.
Also a thing i wish for is a WYSIWYG window for image arrangement and text input + formating etc. This would be a boon for the workflow i believe.

**Comment by jebedaia360** [comment]
@Dogeek 
I run version from last release.

@madeddy 
You are right now it works when run whit out `-m`

**Comment by jebedaia360** [comment]
@madeddy @Dogeek 
Correction it only seams to work when I try to open exmaple project form test folder nothing happens after opening it. I got this in console:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/jeremi360/Apps/renpy-text-editor-0.95b/RTE/controllers/menus.py", line 33, in file_open
    self.master.project = Project(path)
  File "/home/jeremi360/Apps/renpy-text-editor-0.95b/RTE/models/project.py", line 10, in __init__
    self.repo = git.Repo(path=path)
  File "/home/jeremi360/.local/lib/python3.6/site-packages/git/repo/base.py", line 184, in __init__
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: /home/jeremi360/Apps/renpy-text-editor-0.95b
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/jeremi360/Apps/renpy-text-editor-0.95b/RTE/controllers/menus.py", line 33, in file_open
    self.master.project = Project(path)
  File "/home/jeremi360/Apps/renpy-text-editor-0.95b/RTE/models/project.py", line 10, in __init__
    self.repo = git.Repo(path=path)
  File "/home/jeremi360/.local/lib/python3.6/site-packages/git/repo/base.py", line 184, in __init__
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: /home/jeremi360/Apps/renpy-text-editor-0.95b/tests/project
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/jeremi360/Apps/renpy-text-editor-0.95b/RTE/controllers/menus.py", line 33, in file_open
    self.master.project = Project(path)
  File "/home/jeremi360/Apps/renpy-text-editor-0.95b/RTE/models/project.py", line 10, in __init__
    self.repo = git.Repo(path=path)
  File "/home/jeremi360/.local/lib/python3.6/site-packages/git/repo/base.py", line 184, in __init__
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: /home/jeremi360/Apps/renpy-text-editor-0.95b/tests
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/jeremi360/Apps/renpy-text-editor-0.95b/RTE/controllers/menus.py", line 33, in file_open
    self.master.project = Project(path)
  File "/home/jeremi360/Apps/renpy-text-editor-0.95b/RTE/models/project.py", line 10, in __init__
    self.repo = git.Repo(path=path)
  File "/home/jeremi360/.local/lib/python3.6/site-packages/git/repo/base.py", line 184, in __init__
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: /home/jeremi360/Apps/renpy-text-editor-0.95b/tests/the_question
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/jeremi360/Apps/renpy-text-editor-0.95b/RTE/controllers/menus.py", line 33, in file_open
    self.master.project = Project(path)
  File "/home/jeremi360/Apps/renpy-text-editor-0.95b/RTE/models/project.py", line 10, in __init__
    self.repo = git.Repo(path=path)
  File "/home/jeremi360/.local/lib/python3.6/site-packages/git/repo/base.py", line 184, in __init__
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: /home/jeremi360/Apps/renpy-text-editor-0.95b/tests/the_question/game
```
